########################### SERVICES
services:
  api:
    image: pw45s-server
    container_name: pw45s-server
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      #Server Config
      - SERVER_PORT=${SERVER_PORT}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - CLIENT_URL=${CLIENT_URL}
      #Database
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      #Google Oauth
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      #Minio
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_SECURE=${MINIO_SECURE}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      #Time Zone
      - TZ=America/Sao_Paulo
    ports:
      - "8080:8080"
    restart: unless-stopped
    labels:
      # Traefik Config
      - "traefik.enable=true"
      - "traefik.http.routers.pw45s-server.rule=Host(`api.viniciuspegorini.com.br`)"
      - "traefik.http.routers.pw45s-server.tls.certresolver=letsencrypt"
      - "traefik.http.routers.pw45s-server.entrypoints=websecure"
    networks:
      - web
      - database

########################### NETWORKS
networks:
  web:
    name: web
    driver: bridge
    external: true
    attachable: true
  database:
    name: database
    driver: bridge
    external: false
    attachable: true