server:
  port: ${SERVER_PORT:8080}
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        format_sql: false
    show-sql: true
  flyway:
    baseline-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
logging:
  file:
    name: application.log
minio:
  endpoint: ${MINIO_ENDPOINT:http://127.0.0.1:9000}
  port: ${MINIO_PORT:9000}
  accessKey: ${MINIO_ACCESS_KEY:minio@admin} #Login Account
  secretKey: ${MINIO_SECRET_KEY:minio@admin} # Login Password
  secure: ${MINIO_SECURE:false}
  bucket-name: ${MINIO_BUCKET_NAME:pw45s} # Bucket Name
  image-size: 10485760 #  Maximum size of picture file
  file-size: 104857600 #  Maximum file size
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgresql:5432/pw45s}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:/db/prod
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:pw45s-dev
    generate-unique-name: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:/db/dev
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    locations: classpath:/db/test